# Generated by Django 2.2.7 on 2020-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='subtotal',
            new_name='ico',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='is_iva',
            new_name='is_promo',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='subtotal',
            new_name='home_delivery',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='duties',
        ),
        migrations.AddField(
            model_name='detail',
            name='iva',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retefuente',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reteica',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reteiva',
            field=models.FloatField(default=0.0),
        ),
    ]
