# Generated by Django 2.2.7 on 2020-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='date_record',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_record',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
