# Generated by Django 2.2.7 on 2020-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_auto_20200912_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date_record',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_record',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
    ]
