# Generated by Django 2.2.7 on 2020-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_auto_20200912_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
