# Generated by Django 2.2.7 on 2020-09-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_remove_pay_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice_app.Invoice'),
            preserve_default=False,
        ),
    ]
