# Generated by Django 2.2.7 on 2020-09-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_pay_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_record',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_update',
            field=models.DateTimeField(),
        ),
    ]
