# Generated by Django 2.2.7 on 2020-09-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_sale_util'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
