# Generated by Django 2.2.7 on 2020-09-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_detail_is_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date_record',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_record',
            field=models.DateField(),
        ),
    ]
