# Generated by Django 2.2.7 on 2020-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_auto_20200915_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date_update',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_update',
            field=models.DateField(),
        ),
    ]
