# Generated by Django 2.2.7 on 2020-09-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0009_auto_20200915_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date_record',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='buy',
            name='date_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_record',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_update',
            field=models.DateTimeField(),
        ),
    ]
