# Generated by Django 2.2.7 on 2020-09-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaproduct',
            name='presentations',
            field=models.ManyToManyField(blank=True, through='product_app.Product', to='product_app.Presentation'),
        ),
    ]
