# Generated by Django 2.2.7 on 2020-09-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duty',
        ),
        migrations.RemoveField(
            model_name='metaproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='metaproduct',
            name='presentations',
        ),
        migrations.RemoveField(
            model_name='metaproduct',
            name='trademark',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_app.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_record',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('ref', 'amount')},
        ),
        migrations.DeleteModel(
            name='Trademark',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_atomic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metaproduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='providers',
        ),
        migrations.DeleteModel(
            name='Metaproduct',
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
    ]
