# Generated by Django 2.2.7 on 2020-09-12 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_auto_20200910_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trademark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Trademark'),
        ),
    ]
