# Generated by Django 2.2.7 on 2020-09-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_adviser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Provider'),
        ),
    ]
