# Generated by Django 2.2.7 on 2020-09-06 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20200906_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviser',
            options={'verbose_name': 'Asesor', 'verbose_name_plural': 'Asesores'},
        ),
        migrations.AddField(
            model_name='adviser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
