export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_PROVIDERS = 'GET_PROVIDERS';
export const GET_CLIENTS = 'GET_CLIENTS';

export const ACTION_RUNNING = 'ACTION_RUNNING';
export const ACTION_END = 'ACTION_END';

export const ADD_SALE = 'ADD_SALE';
export const UPDATE_SALE = 'UPDATE_SALE';
export const REMOVE_SALE = 'REMOVE_SALE';
export const GET_SALES = 'GET_SALES';

export const ADD_BUY = 'ADD_BUY';
export const UPDATE_BUY = 'UPDATE_BUY';
export const REMOVE_BUY = 'REMOVE_BUY';
export const GET_BUYS = 'GET_BUYS';

export const ADD_METAPRODUCT = 'ADD_METAPRODUCT';
export const UPDATE_METAPRODUCT = 'UPDATE_METAPRODUCT';
export const REMOVE_METAPRODUCT = 'REMOVE_METAPRODUCT';
export const GET_METAPRODUCTS = 'GET_METAPRODUCTS';
export const RESET_METAPRODUCTS = 'RESET_METAPRODUCTS';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const RESET_PRODUCTS = 'RESET_PRODUCTS';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const RESET_CATEGORIES = 'RESET_CATEGORIES';

export const GET_TRADEMARKS = 'GET_TRADEMARKS';
export const RESET_TRADEMARKS = 'RESET_TRADEMARKS';

export const GET_PRESENTATIONS = 'GET_PRESENTATIONS';
export const RESET_PRESENTATIONS = 'RESET_PRESENTATIONS';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS';
